# Dependabot configuration for automated dependency updates
# This ensures dependencies stay secure and up-to-date

version: 2
updates:
  # Enable version updates for npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    assignees:
      - "yama-dev-team"
    reviewers:
      - "yama-dev-team"
    labels:
      - "dependencies"
      - "automated"
    commit-message:
      prefix: "deps"
      include: "scope"
    # Group updates for easier review
    groups:
      major-updates:
        patterns:
          - "*"
        update-types:
          - "major"
      minor-updates:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    # Ignore specific packages that require manual review
    ignore:
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-major"]
      - dependency-name: "typescript"
        update-types: ["version-update:semver-major"]
      - dependency-name: "eslint"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@juspay/neurolink"
        update-types: ["version-update:semver-major"]

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:30"
    open-pull-requests-limit: 3
    assignees:
      - "yama-dev-team"
    reviewers:
      - "yama-dev-team"
    labels:
      - "github-actions"
      - "dependencies"
      - "automated"
    commit-message:
      prefix: "ci"
      include: "scope"
