/**
 * `yama migrate` — split a v3 config into the v4 file tree.
 *
 * Uses the same adaptation the loader uses at runtime, so what `migrate` writes
 * and what the loader would have inferred can never drift apart.
 *
 * The output is a plan, not a write. Callers show it, then write it. A config
 * migration that silently rewrites files is a migration nobody trusts.
 */

import { stringify as stringifyYAML } from "yaml";
import { adaptV3Config } from "./v3Compat.js";
import type { MigrationFile, MigrationPlan } from "../types/index.js";

const header = (title: string, note: string): string =>
  `# ${title}\n# ${note}\n# Generated by \`yama migrate\`. Review before committing.\n\n`;

/**
 * Build the migration plan.
 *
 * `orphans` are the interesting part: v3's `focusAreas` and
 * `workflowInstructions` were prompt text, and v4 has no prompt to put them in.
 * They become knowledge files the agent retrieves on demand — which is a real
 * behaviour change, so it is surfaced rather than performed quietly.
 */
export function buildMigrationPlan(legacy: unknown): MigrationPlan {
  const adapted = adaptV3Config(legacy);
  const files: MigrationFile[] = [];

  files.push({
    path: ".yama/yama.yaml",
    content:
      header(
        "Yama core configuration",
        "Models, fallback chains, and learning.",
      ) + stringifyYAML(adapted.yama),
    from: "ai.*, state.*",
  });

  files.push({
    path: ".yama/mcp.yaml",
    content:
      header(
        "Connections",
        "Each server maps capabilities to the tool names it provides.",
      ) + stringifyYAML(adapted.mcp),
    from: "mcpServers.servers.*",
  });

  if (adapted.review) {
    files.push({
      path: ".yama/review.yaml",
      content:
        header(
          "Review behaviour",
          "excludePatterns and maxFiles are now enforced in code, not requested in a prompt.",
        ) + stringifyYAML(adapted.review),
      from: "review.excludePatterns, review.maxFilesPerReview, review.verification",
    });
  }

  for (const orphan of adapted.orphans) {
    files.push({
      path: orphan.suggestedPath,
      content: `${orphan.content}\n`,
      from: orphan.from,
    });
  }

  return {
    files,
    dropped: collectDropped(legacy),
    notices: adapted.notices,
    orphans: adapted.orphans,
  };
}

/** v3 keys that no v4 code reads. Reported so nobody keeps maintaining them. */
const DROPPED_KEYS: Array<{ key: string; why: string }> = [
  { key: "performance.tokenBudget", why: "never enforced in v3 either" },
  { key: "performance.costControls", why: "never enforced in v3 either" },
  {
    key: "performance.maxReviewDuration",
    why: "v4 bounds a review by work, not by a clock; set review.deadline if you need a hard cap",
  },
  {
    key: "review.toolPreferences",
    why: "was prompt advice; v4 has no prompt to put it in",
  },
  { key: "review.contextLines", why: "the diff is parsed in code now" },
  {
    key: "review.fileAnalysisTimeout",
    why: "per-file timeouts are replaced by stall detection",
  },
  { key: "descriptionEnhancement.autoFormat", why: "no longer meaningful" },
];

function collectDropped(legacy: unknown): string[] {
  if (!legacy || typeof legacy !== "object") {
    return [];
  }
  return DROPPED_KEYS.filter(({ key }) => {
    let cursor: unknown = legacy;
    for (const part of key.split(".")) {
      if (!cursor || typeof cursor !== "object") {
        return false;
      }
      cursor = (cursor as Record<string, unknown>)[part];
    }
    return cursor !== undefined;
  }).map(({ key, why }) => `${key} — ${why}`);
}

/** The "what moved where" table. */
export function renderMigrationPlan(plan: MigrationPlan): string {
  const lines = ["Migration plan", "", "| New file | From |", "| --- | --- |"];

  for (const file of plan.files) {
    lines.push(`| ${file.path} | ${file.from} |`);
  }

  if (plan.dropped.length > 0) {
    lines.push("", "Dropped (accepted by v3, read by nothing):");
    for (const key of plan.dropped) {
      lines.push(`  - ${key}`);
    }
  }

  if (plan.orphans.length > 0) {
    lines.push(
      "",
      "Prompt text with no v4 equivalent — written to .yama/knowledge/ where the",
      "agent retrieves it on demand rather than carrying it on every turn:",
    );
    for (const orphan of plan.orphans) {
      lines.push(`  - ${orphan.from} → ${orphan.suggestedPath}`);
    }
  }

  const warnings = plan.notices.filter((notice) => notice.level === "warn");
  if (warnings.length > 0) {
    lines.push("", "Warnings:");
    for (const notice of warnings) {
      lines.push(`  - ${notice.message}`);
    }
  }

  lines.push(
    "",
    "Your existing config keeps working until you delete it. Nothing here is",
    "written until you pass --write.",
  );

  return lines.join("\n");
}

/**
 * Import an existing CODEOWNERS file.
 *
 * `exclusive: true` on every rule preserves CODEOWNERS' last-match-wins
 * semantics. Without it the import would silently change who must approve what,
 * which is exactly the kind of surprise an ownership file must never spring.
 */
export function importCodeowners(content: string): {
  rules: Array<{
    id: string;
    paths: string[];
    owners: string[];
    minApprovals: number;
    blocking: boolean;
    exclusive: boolean;
  }>;
  skipped: string[];
} {
  const rules: ReturnType<typeof importCodeowners>["rules"] = [];
  const skipped: string[] = [];

  for (const [index, raw] of content.split("\n").entries()) {
    const line = raw.replace(/#.*$/, "").trim();
    if (line.length === 0) {
      continue;
    }
    const [pattern, ...owners] = line.split(/\s+/);
    if (!pattern || owners.length === 0) {
      skipped.push(`line ${index + 1}: ${raw.trim()}`);
      continue;
    }
    rules.push({
      id: `codeowners-${index + 1}`,
      // CODEOWNERS patterns are gitignore-flavoured: a bare directory means
      // everything under it, and a leading slash anchors to the root.
      paths: [normalizeCodeownersPattern(pattern)],
      owners,
      minApprovals: 1,
      // Imported as non-blocking: CODEOWNERS enforcement is a branch-protection
      // setting, and silently turning it into a Yama gate would change merge
      // behaviour the moment the file is imported.
      blocking: false,
      exclusive: true,
    });
  }

  return { rules, skipped };
}

function normalizeCodeownersPattern(pattern: string): string {
  let normalized = pattern.startsWith("/") ? pattern.slice(1) : `**/${pattern}`;
  if (normalized.endsWith("/")) {
    normalized = `${normalized}**`;
  } else if (!normalized.includes("*") && !normalized.includes(".")) {
    // A bare directory name covers everything beneath it.
    normalized = `${normalized}/**`;
  }
  return normalized;
}
